UPDATE "RMFs" SET 
    "RU_NRW" = 0
    "RU_TotalBilled" = 0
    "RU_WaterPipelineConstructed" = 0
    "RU_NWCIndividualConnection" = 0
    "RU_NWCYardTaps" = 0
    "RU_NWCMDU" = 0
    "RU_NWCKiosks" = 0
    "RU_Newbeneficiaries_NewConnections" = 0
    "RU_Beneficiaries_ImprovedService" = 0
    "RU_Newbeneficiaries_ProtectedSprings" = 0
    "RU_Beneficiaries_IS_ProtectedSprings" = 0
    "RU_WaterProduced" = 0
    "RU_WaterStorage" = 0
    "RU_SupplyHours" = 0
    "RU_New_Meters" = 0
    "WRM_PES_Actions" = 0
    "WRM_Trees_Planted" = 0
    "WRM_Springs_Protected" = 0
    "WRM_Terrace_Kilometers" = 0
    "WRM_Riparian_Rehabilitated" = 0
    "WRM_Forest_Rehabilitated" = 0
    "WRM_WRUAs_SCMP" = 0
    "WRM_Tree_Nurseries" = 0
    "WRM_Riverine_Protected" = 0
    "WRM_Beneficiaries_Improved_WRM" = 0
    "WRM_Beneficiaries_IGA_HH" = 0
    "WRM_Beneficiaries_IGA_Total" = 0
    "WRM_WRUA_Committees_Trained" = 0
    "FPS_PrivateFunding_Own" = 0
    "FPS_PrivateFunding_Debt" = 0
    "FPS_PhilanthropicFunding" = 0
    "FPS_PublicFunding_CountyGov" = 0
    "FPS_PublicFunding_NationalGov" = 0
    "FPS_NewBeneficiaries_PrivateFunding" = 0
    "FPS_IS_Beneficiaries_PrivateFunding" = 0
    "FPS_NewBeneficiaries_PhilanthropicFunding" = 0
    "FPS_IS_Beneficiaries_PhilanthropicFunding" = 0
    "FPS_NewBeneficiaries_PublicFunding" = 0
    "FPS_IS_Beneficiaries_PublicFunding" = 0
    "PG_ProPoorPolicies_Developed" = 0
    "PG_MeteringPolicies_Developed" = 0
    "PG_ClimateChangePolicies_Developed" = 0
    "PG_MarketingPolicies_Developed" = 0
    "PG_BusinessPlans_Developed" = 0
    "PG_WaterSafetyPlan_Developed" = 0
    "PG_PIPs_Developed" = 0
    "PG_CIDP_Developed" = 0
    "PG_WaterSanitationAct_Developed" = 0
    "PG_NRWManual_Developed" = 0
    "PG_ServiceCharter_Developed" = 0
    "PG_Officials_Trained" = 0
WHERE
    "RU_TotalBilled" IS NULL;
    "RU_WaterPipelineConstructed" IS NULL;
    "RU_NWCIndividualConnection" IS NULL;
    "RU_NWCYardTaps" IS NULL;
    "RU_NWCMDU" IS NULL;
    "RU_NWCKiosks" IS NULL;
    "RU_Newbeneficiaries_NewConnections" IS NULL;
    "RU_Beneficiaries_ImprovedService" IS NULL;
    "RU_Newbeneficiaries_ProtectedSprings" IS NULL;
    "RU_Beneficiaries_IS_ProtectedSprings" IS NULL;
    "RU_WaterProduced" IS NULL;
    "RU_WaterStorage" IS NULL;
    "RU_SupplyHours" IS NULL;
    "RU_New_Meters" IS NULL;
    "WRM_PES_Actions" IS NULL;
    "WRM_Trees_Planted" IS NULL;
    "WRM_Springs_Protected" IS NULL;
    "WRM_Terrace_Kilometers" IS NULL;
    "WRM_Riparian_Rehabilitated" IS NULL;
    "WRM_Forest_Rehabilitated" IS NULL;
    "WRM_WRUAs_SCMP" IS NULL;
    "WRM_Tree_Nurseries" IS NULL;
    "WRM_Riverine_Protected" IS NULL;
    "WRM_Beneficiaries_Improved_WRM" IS NULL;
    "WRM_Beneficiaries_IGA_HH" IS NULL;
    "WRM_Beneficiaries_IGA_Total" IS NULL;
    "WRM_WRUA_Committees_Trained" IS NULL;
    "FPS_PrivateFunding_Own" IS NULL;
    "FPS_PrivateFunding_Debt" IS NULL;
    "FPS_PhilanthropicFunding" IS NULL;
    "FPS_PublicFunding_CountyGov" IS NULL;
    "FPS_PublicFunding_NationalGov" IS NULL;
    "FPS_NewBeneficiaries_PrivateFunding" IS NULL;
    "FPS_IS_Beneficiaries_PrivateFunding" IS NULL;
    "FPS_NewBeneficiaries_PhilanthropicFunding" IS NULL;
    "FPS_IS_Beneficiaries_PhilanthropicFunding" IS NULL;
    "FPS_NewBeneficiaries_PublicFunding" IS NULL;
    "FPS_IS_Beneficiaries_PublicFunding" IS NULL;
    "PG_ProPoorPolicies_Developed" IS NULL;
    "PG_MeteringPolicies_Developed" IS NULL;
    "PG_ClimateChangePolicies_Developed" IS NULL;
    "PG_MarketingPolicies_Developed" IS NULL;
    "PG_BusinessPlans_Developed" IS NULL;
    "PG_WaterSafetyPlan_Developed" IS NULL;
    "PG_PIPs_Developed" IS NULL;
    "PG_CIDP_Developed" IS NULL;
    "PG_WaterSanitationAct_Developed" IS NULL;
    "PG_NRWManual_Developed" IS NULL;
    "PG_ServiceCharter_Developed" IS NULL;
    "PG_Officials_Trained" IS NULL;